# Generated by Django 4.0.4 on 2022-05-19 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Compliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=255)),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='due_dates.act')),
            ],
        ),
        migrations.CreateModel(
            name='Due_Date_Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Relevant_Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('start_year', models.IntegerField()),
                ('end_month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('end_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Due',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='due_dates.compliance')),
                ('relevant_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='due_dates.relevant_period')),
            ],
        ),
        migrations.AddField(
            model_name='compliance',
            name='due_date_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='due_dates.due_date_types'),
        ),
    ]
