# Generated by Django 4.0.4 on 2022-05-19 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('due_dates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='due',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='due',
            name='dueon',
            field=models.DateField(default=datetime.date(2022, 5, 19)),
        ),
    ]
